### ISSUE TITLE
Distribution request

### ISSUE THREAD

**Issue by archey** [enigma0x3/Powershell-Payload-Excel-Delivery#1]
I am a developer for the ArchAssault Project(https://archassault.org), we would like to distribute your powershell scripts. However I noticed that they are missing a license file, can you please add a license file and give us permission to distribute your project?

**Comment by enigma0x3** [comment]
Thank you for your interest in my work. I have added a license file in the root of the repo. I also give you permission to distribute the project. Let me know if you need anything :)
